[build-system]
   requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
   build-backend = "setuptools.build_meta"

[project]
   name = "blehrm"
   version = "0.1.0"
   # ... other metadata ...

[tool.setuptools.packages.find]
   where = ["."]
   include = ["blehrm*"]